{
 "title": "GHOSTS 5",
 "time": { "from": "2021-10-01T12:17:30.079Z", "to": "2021-10-01T12:56:45.763Z" },
 "panels": [
  {
   "title": "NPCs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "rawSql": "SELECT COUNT(*) FROM machines;" }
   ]
  },
  {
   "title": "ACTIVITIES",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM history_timeline;"
    }
   ]
  },
  {
   "title": "POLLING",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM history_machine;"
    }
   ]
  },
  {
   "title": "HEALTH",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM history_health;"
    }
   ]
  },
  {
   "title": "ALL ACTIVITIES",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(createdutc, '5m', 0),\n  count(*) as \"Timeline\"\nFROM\n  history_timeline\nWHERE \n  $__timeFilter(createdutc)\nGROUP BY \n  time\nORDER BY \n  time\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(createdutc, '5m', 0),\n  count(*) as \"Health\"\nFROM\n  history_health\nWHERE \n  $__timeFilter(createdutc)\nGROUP BY \n  time\nORDER BY \n  time\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(createdutc, '5m', 0),\n  count(*) as \"Polls\"\nFROM\n  history_machine\nWHERE \n  $__timeFilter(createdutc)\nGROUP BY \n  time\nORDER BY \n  time\n"
    }
   ]
  },
  {
   "title": "TIMELINE BREAKDOWN",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  handler as \"Handler\",\n  count(*) as \"Executions\",\n  date_trunc('minute', createdutc) as \"time\"\nFROM\n  history_timeline\ngroup by handler, date_trunc('minute', createdutc) \norder by date_trunc('minute', createdutc) ASC\n"
    }
   ]
  },
  {
   "title": "TIMELINE TOTALS",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT handler as \"Handler\", count(*) as \"Executions\" from history_timeline group by handler;"
    }
   ]
  },
  {
   "title": "LAST REPORTING",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT name as \"Machine\", 'Up' as \"Status\", lastreportedutc as \"Time\" from machines order by lastreportedutc desc limit 8;"
    }
   ]
  }
 ]
}